// Frontier Communications coverage data
// Maps state names to arrays of city names where Frontier provides service

export const frontierCoverage: Record<string, string[]> = {
  Arizona: [
    "Phoenix",
    "Tucson",
    "Scottsdale",
    "Mesa",
    "Chandler",
  ],
  California: [
    "Los Angeles",
    "San Francisco",
    "San Diego",
    "San Jose",
    "Sacramento",
    "Fresno",
    "Long Beach",
    "Oakland",
    "Bakersfield",
    "Anaheim",
    "Santa Ana",
    "Riverside",
    "Stockton",
    "Irvine",
    "Chula Vista",
    "Moreno Valley",
    "Fontana",
    "Glendale",
    "Santa Clarita",
    "Garden Grove",
    "Oceanside",
    "Rancho Cucamonga",
    "Ontario",
    "Santa Rosa",
    "Elk Grove",
    "Corona",
    "Lancaster",
    "Palmdale",
    "Salinas",
    "Pomona",
    "Hayward",
    "Escondido",
    "Sunnyvale",
    "Torrance",
    "Pasadena",
    "Orange",
    "Fullerton",
    "Thousand Oaks",
    "Roseville",
    "Concord",
    "Simi Valley",
    "Santa Clara",
    "Victorville",
    "Vallejo",
    "Berkeley",
    "El Monte",
    "Downey",
    "Costa Mesa",
    "Inglewood",
    "Carlsbad",
    "San Buenaventura",
    "Fairfield",
    "West Covina",
    "Murrieta",
    "Richmond",
    "Norwalk",
    "Antioch",
    "Temecula",
    "Burbank",
    "Daly City",
    "El Cajon",
    "San Mateo",
    "Rialto",
    "Clovis",
    "Compton",
    "Jurupa Valley",
    "Vista",
    "South Gate",
    "Mission Viejo",
    "Vacaville",
    "Carson",
    "Hesperia",
    "Santa Maria",
    "Redding",
    "Westminster",
    "Santa Monica",
    "Chico",
    "Newport Beach",
    "San Leandro",
    "San Marcos",
    "Whittier",
    "Hawthorne",
    "Citrus Heights",
    "Alhambra",
    "Tracy",
    "Livermore",
    "Buena Park",
    "Menifee",
    "Hemet",
    "Lakewood",
    "Merced",
    "Chino",
    "Indio",
    "Redwood City",
    "Lake Forest",
    "Napa",
    "Tustin",
    "Bellflower",
    "Mountain View",
    "Chino Hills",
    "Baldwin Park",
    "Alameda",
    "Upland",
    "San Ramon",
    "Folsom",
    "Pleasanton",
    "Lynwood",
    "Union City",
    "Apple Valley",
    "Redlands",
    "Turlock",
  ],
  Connecticut: [
    "Bridgeport",
    "New Haven",
    "Stamford",
    "Hartford",
    "Waterbury",
    "Norwalk",
    "Danbury",
    "New Britain",
    "West Hartford",
    "Greenwich",
    "Fairfield",
    "Hamden",
    "Bristol",
    "Meriden",
    "Manchester",
    "West Haven",
    "Milford",
    "Stratford",
    "East Hartford",
    "Middletown",
    "Wallingford",
    "Enfield",
    "Glastonbury",
    "Southington",
    "Shelton",
    "Groton",
    "Naugatuck",
    "Trumbull",
    "Torrington",
    "Vernon",
    "Newington",
    "Windsor",
    "Cheshire",
    "Branford",
    "Newtown",
    "Westport",
    "Farmington",
    "Ridgefield",
    "Simsbury",
  ],
  Florida: [
    "Tampa",
    "Orlando",
    "Jacksonville",
    "Miami",
    "Fort Lauderdale",
    "St. Petersburg",
    "Hialeah",
    "Tallahassee",
    "Port St. Lucie",
    "Cape Coral",
    "Pembroke Pines",
    "Hollywood",
    "Miramar",
    "Gainesville",
    "Coral Springs",
    "Clearwater",
    "Palm Bay",
    "Lakeland",
    "Pompano Beach",
    "West Palm Beach",
    "Davie",
    "Boca Raton",
    "Sunrise",
    "Deltona",
    "Plantation",
    "Fort Myers",
    "Palm Coast",
    "Deerfield Beach",
    "Largo",
    "Melbourne",
    "Boynton Beach",
    "Lauderhill",
    "Weston",
    "Kissimmee",
    "Homestead",
    "Delray Beach",
    "Tamarac",
    "Daytona Beach",
    "North Miami",
    "Wellington",
    "Jupiter",
    "Coconut Creek",
    "Sanford",
    "Margate",
    "Ocala",
  ],
  Georgia: [
    "Atlanta",
  ],
  Illinois: [
    "Chicago",
    "Aurora",
    "Naperville",
    "Joliet",
    "Rockford",
  ],
  Indiana: [
    "Indianapolis",
    "Fort Wayne",
    "Evansville",
    "South Bend",
    "Carmel",
    "Fishers",
    "Bloomington",
    "Hammond",
    "Gary",
  ],
  Iowa: [
    "Des Moines",
  ],
  Minnesota: [
    "Minneapolis",
    "St. Paul",
    "Rochester",
    "Duluth",
    "Bloomington",
    "Brooklyn Park",
    "Plymouth",
    "Maple Grove",
    "Woodbury",
    "St. Cloud",
    "Eagan",
    "Eden Prairie",
    "Coon Rapids",
    "Burnsville",
    "Blaine",
    "Lakeville",
    "Minnetonka",
    "Apple Valley",
  ],
  Nebraska: [
    "Omaha",
  ],
  Nevada: [
    "Las Vegas",
  ],
  "New York": [
    "New York City",
    "Buffalo",
    "Rochester",
    "Yonkers",
    "Syracuse",
    "Albany",
    "New Rochelle",
    "Mount Vernon",
    "Schenectady",
    "Utica",
    "White Plains",
    "Troy",
    "Niagara Falls",
    "Binghamton",
    "Freeport",
    "Valley Stream",
    "Long Beach",
    "Spring Valley",
    "Rome",
    "Ithaca",
    "North Tonawanda",
    "Poughkeepsie",
    "Jamestown",
    "Elmira",
    "Cortland",
    "Kingston",
    "Amsterdam",
    "Plattsburgh",
    "Glens Falls",
    "Saratoga Springs",
    "Oneonta",
    "Batavia",
    "Ogdensburg",
    "Oswego",
    "Geneva",
    "Fulton",
    "Oneida",
    "Dunkirk",
    "Gloversville",
    "Norwich",
    "Canandaigua",
    "Watervliet",
    "Hornell",
    "Mechanicville",
    "Little Falls",
    "Hudson",
    "Corning",
    "Cohoes",
    "Tonawanda",
    "Lackawanna",
    "Depew",
    "Kenmore",
    "Massena",
    "Potsdam",
    "Malone",
    "Olean",
    "Salamanca",
    "Wellsville",
    "Penn Yan",
    "Seneca Falls",
    "Medina",
    "Albion",
    "Geneseo",
    "Brockport",
    "Fredonia",
    "Westfield",
    "Hamburg",
    "East Aurora",
    "Williamsville",
    "Orchard Park",
    "Lancaster",
    "Cheektowaga",
    "West Seneca",
    "Clarence",
    "Amherst",
    "Grand Island",
    "Lewiston",
    "Lockport",
    "Middletown",
    "Newburgh",
    "Beacon",
    "Peekskill",
    "Ossining",
    "Tarrytown",
    "Dobbs Ferry",
    "Hastings On Hudson",
    "Mamaroneck",
    "Larchmont",
    "Rye",
    "Port Chester",
    "Harrison",
    "Bronxville",
    "Tuckahoe",
    "Eastchester",
    "Pelham",
    "Scarsdale",
    "Pleasantville",
    "Briarcliff Manor",
    "Croton On Hudson",
  ],
  "North Carolina": [
    "Charlotte",
    "Raleigh",
    "Durham",
  ],
  Ohio: [
    "Columbus",
    "Cleveland",
    "Cincinnati",
    "Toledo",
    "Akron",
    "Dayton",
    "Parma",
    "Canton",
    "Youngstown",
    "Lorain",
    "Hamilton",
    "Springfield",
    "Kettering",
  ],
  Pennsylvania: [
    "Philadelphia",
    "Pittsburgh",
    "Allentown",
    "Erie",
    "Reading",
    "Scranton",
  ],
  "South Carolina": [
    "Charleston",
    "Columbia",
  ],
  Tennessee: [
    "Nashville",
  ],
  Texas: [
    "Dallas",
    "Houston",
    "San Antonio",
    "Austin",
    "Fort Worth",
    "El Paso",
    "Arlington",
    "Corpus Christi",
    "Plano",
    "Laredo",
    "Lubbock",
    "Garland",
    "Irving",
    "Amarillo",
    "Grand Prairie",
    "Brownsville",
    "McKinney",
    "Frisco",
    "Pasadena",
    "Mesquite",
    "Killeen",
    "McAllen",
    "Midland",
    "Denton",
    "Carrollton",
    "Round Rock",
    "Waco",
    "Abilene",
    "Odessa",
    "Pearland",
    "Richardson",
    "Sugar Land",
    "Allen",
    "Beaumont",
    "Lewisville",
    "Tyler",
    "San Angelo",
    "Wichita Falls",
  ],
  "West Virginia": [
    "Charleston",
    "Huntington",
    "Morgantown",
    "Parkersburg",
  ],
}
