export const testimonials = [
  {
    id: 1,
    name: "Maria Santos",
    location: "Dallas, TX",
    rating: 5,
    date: "2025-02-03",
    text: "Switched from cable to Frontier Fiber and couldn't be happier. The upload speeds are game-changing for my video editing work. No more waiting hours to upload to the cloud. Highly recommend!",
    avatar: "MS",
    verified: true,
  },
  {
    id: 2,
    name: "James Chen",
    location: "Phoenix, AZ",
    rating: 5,
    date: "2025-01-28",
    text: "Been a Frontier customer for 6 months now. The installation was quick and professional. Support has been responsive when I had questions. Best internet speeds I've ever had.",
    avatar: "JC",
    verified: true,
  },
  {
    id: 3,
    name: "Lisa Rodriguez",
    location: "Tampa, FL",
    rating: 5,
    date: "2025-01-15",
    text: "As a small business owner running Zoom calls and streaming, Frontier Fiber has been rock solid. No drops, no lag, and the unlimited data means I never worry about going over.",
    avatar: "LR",
    verified: true,
  },
  {
    id: 4,
    name: "David Park",
    location: "San Antonio, TX",
    rating: 5,
    date: "2025-01-08",
    text: "My family loves our new Fiber connection. Gaming is smooth, 4K streaming on multiple TVs works flawlessly, and my kids can video chat while I work from home. Fantastic value.",
    avatar: "DP",
    verified: true,
  },
  {
    id: 5,
    name: "Angela Martinez",
    location: "Houston, TX",
    rating: 5,
    date: "2024-12-20",
    text: "Finally ditched my cable company. Frontier has better speeds, no data caps, and the equipment is included. Why didn't I switch earlier? So worth it.",
    avatar: "AM",
    verified: true,
  },
  {
    id: 6,
    name: "Michael Thompson",
    location: "Austin, TX",
    rating: 5,
    date: "2024-12-10",
    text: "Installation was seamless, speeds are incredible, and customer service actually picked up on the first try. This is what good internet should be. No regrets.",
    avatar: "MT",
    verified: true,
  },
]
